{"uid":"f44bee5d250729e6","name":"Test to verify that user can complete the job with exception when task are paused and completed with exception ","fullName":"tests.scenarios.job.test_job_execution.TestJobExecution#test_complete_job_having_pause_task_with_exception","historyId":"5c14922ac08221d1d2ff967e8c36f4a6","time":{"start":1733761294065,"stop":1733761294065,"duration":0},"description":"This testcase tests completing job with exception when task are paused and completed with exception","descriptionHtml":"<p>This testcase tests completing job with exception when task are paused and completed with exception</p>\n","status":"skipped","statusMessage":"Skipped: We cannot complete the job with exception when task are paused","statusTrace":"('/home/server1/Downloads/platform-api-develop/tests/scenarios/job/test_job_execution.py', 1446, 'Skipped: We cannot complete the job with exception when task are paused')","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[{"name":"env_setup","time":{"start":1733752687376,"stop":1733752687376,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"login_fixture","time":{"start":1733752687376,"stop":1733752687642,"duration":266},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"get_facility","time":{"start":1733752687642,"stop":1733752687801,"duration":159},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"select_usecase_fixture","time":{"start":1733752687801,"stop":1733752687918,"duration":117},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"username_to_user_id_mapping","time":{"start":1733752687918,"stop":1733752688451,"duration":533},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"user_group_creation","time":{"start":1733760133164,"stop":1733760133769,"duration":605},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"flush_param_counters","time":{"start":1733761294066,"stop":1733761294066,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"flush_param_counters::0","time":{"start":1733761305291,"stop":1733761305291,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.skip(reason='We cannot complete the job with exception when task are paused')"},{"name":"tag","value":"complete_job_having_pause_task_with_exception"},{"name":"tag","value":"job"},{"name":"tag","value":"scenario"},{"name":"parentSuite","value":"tests.scenarios.job"},{"name":"suite","value":"test_job_execution"},{"name":"subSuite","value":"TestJobExecution"},{"name":"host","value":"ubuntu"},{"name":"thread","value":"53959-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.scenarios.job.test_job_execution"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"job_execution_by","value":"'user'"},{"name":"users_list","value":"['process.publisher.03']"}],"links":[{"name":"https://app.clickup.com/t/86cukrh1m","url":"https://app.clickup.com/t/86cukrh1m","type":"link"}],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"ce937904621d48f5","status":"skipped","statusDetails":"Skipped: We cannot complete the job with exception when task are paused","time":{"start":1733499021679,"stop":1733499021679,"duration":0}}],"categories":[],"tags":["scenario","@pytest.mark.skip(reason='We cannot complete the job with exception when task are paused')","job","complete_job_having_pause_task_with_exception"]},"source":"f44bee5d250729e6.json","parameterValues":["'user'","['process.publisher.03']"]}